### ISSUE TITLE
Python Project Issues

### ISSUE THREAD

**Issue by JunruiZhang** [resumejob/free-project-course#10]
1. [Python & Cryptocurrency: Build 5 Real World Applications](https://www.udemy.com/course/coinmarketcap/) is a paid course.
2. [Python Hero: Full Course with Projects](https://www.udemy.com/course/python-guru-complete-course-projects-hindi-urduhd/) is a paid course.
3. [Python Programming - Build a Reconnaissance Scanner](https://www.udemy.com/course/python-programming-build-a-reconnaissance-scanner/) is no longer accepting enrollments.
4. [Practical Python - Part 3 ](https://www.udemy.com/course/practical-python-part-3/) is not a project course.

**Comment by Windsooon** [comment]
Thank you and fixed at https://github.com/resumejob/free-project-course/pull/11
