### ISSUE TITLE
Wrong network link about C/C++

### ISSUE THREAD

**Issue by finetune-master** [resumejob/free-project-course#9]
#### When I was watching the video link of the C/C++ part, I found that most of them cannot be used for learning
1. The video link about 小游戏完整项目制作 disappeared;
2. The video link about 微信飞机大战 disappeared;
3. The video link about 牛B闪闪坦克大战 is music, not learning video about C/C++;
4. C++项目实战 doesn't have code.This problem troubles me;
**That is all the problems I found**

**Comment by Windsooon** [comment]
Thank you. We fixed it at https://github.com/resumejob/free-project-course/pull/12
